server:
  port: 80
spring:
  cloud:
    alicloud:
      access-key: # 阿里云access-key
      secret-key: # 阿里云secret-key
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucketname: yerenping
  application:
    # 项目的名称
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
    #dd
    # redis配置
    redis:
      port: 6379
      host: 127.0.0.1
      #password: 12345
      database: 0
    # 设置缓存过期时间
    cache:
      redis:
        time-to-live: 1800000 # 1800秒 = 30分钟

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID #主键命名策略，雪花算法，全局唯一id
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
file:
  upload:
    localPath: /Users/ouyangyansong/Documents/file/

# 腾讯云短信服务，用于登录与与注册
tx:
  sms:
    smsSign: 是叶十三
    templateId: 1478571
    appid:
    appkey:
 